/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.forms.competition;

import contract.dto.*;
import contract.useCaseController.IChangeCompetitionTeam;
import java.util.LinkedList;
import java.util.List;
import javax.swing.AbstractListModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import javax.swing.ListModel;
import presentation.basics.AbstractForm;
import presentation.basics.AbstractMainForm;
import com.ServiceClient;
import com.ServiceNotAvailableException;

/**
 *
 * @author Lucia
 */
public class ChangeCompetitionTeamForm extends AbstractMainForm {

    IMemberDto user;
    ServiceClient client;
    IChangeCompetitionTeam controller;
    ICompetitionDto competition;
    List<IClubTeamDto> cTeams;
    IClubTeamDto team;
    List<IPlayerDto> teamMember;
    List<IPlayerDto> oldTeam;
    List<IPlayerDto> newTeam;

    /**
     * Creates new form AddTeamMember
     */
    public ChangeCompetitionTeamForm(AbstractForm form, ServiceClient client, IMemberDto user) throws ServiceNotAvailableException {
        super(form);
        this.client = client;
        this.user = user;
        controller = this.client.getChangeCompetitionTeamService();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelChangeTeam = new javax.swing.JPanel();
        lblCompetitionSel = new javax.swing.JLabel();
        comboCompetition = new javax.swing.JComboBox();
        lblSelTeam = new javax.swing.JLabel();
        comboTeam = new javax.swing.JComboBox();
        scrollTeam = new javax.swing.JScrollPane();
        listTeam = new javax.swing.JList();
        lblMembers = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        scrollCompTeam = new javax.swing.JScrollPane();
        listCompTeam = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(845, 549));

        lblCompetitionSel.setText("Competition");

        comboCompetition.setModel(new javax.swing.DefaultComboBoxModel(getCompetitionList()));
        comboCompetition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCompetitionActionPerformed(evt);
            }
        });

        lblSelTeam.setText("Team");

        comboTeam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        comboTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTeamActionPerformed(evt);
            }
        });

        listTeam.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrollTeam.setViewportView(listTeam);

        lblMembers.setText("Team Members");

        btnAdd.setText("Add >");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        listCompTeam.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrollCompTeam.setViewportView(listCompTeam);

        jLabel1.setText("Current Competition Team");

        btnRemove.setText("< Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnSave.setText("Save Team");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelChangeTeamLayout = new javax.swing.GroupLayout(panelChangeTeam);
        panelChangeTeam.setLayout(panelChangeTeamLayout);
        panelChangeTeamLayout.setHorizontalGroup(
            panelChangeTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChangeTeamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelChangeTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelChangeTeamLayout.createSequentialGroup()
                        .addGroup(panelChangeTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCompetitionSel)
                            .addComponent(lblSelTeam))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelChangeTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboCompetition, 0, 200, Short.MAX_VALUE)
                            .addComponent(comboTeam, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelChangeTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSave)
                        .addGroup(panelChangeTeamLayout.createSequentialGroup()
                            .addGroup(panelChangeTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMembers)
                                .addGroup(panelChangeTeamLayout.createSequentialGroup()
                                    .addComponent(scrollTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(panelChangeTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelChangeTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(scrollCompTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(362, Short.MAX_VALUE))
        );
        panelChangeTeamLayout.setVerticalGroup(
            panelChangeTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChangeTeamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelChangeTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompetitionSel)
                    .addComponent(comboCompetition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelChangeTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelTeam))
                .addGap(27, 27, 27)
                .addGroup(panelChangeTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelChangeTeamLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollCompTeam))
                    .addGroup(panelChangeTeamLayout.createSequentialGroup()
                        .addComponent(lblMembers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelChangeTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelChangeTeamLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(btnAdd)
                                .addGap(27, 27, 27)
                                .addComponent(btnRemove))
                            .addComponent(scrollTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelChangeTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelChangeTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboCompetitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCompetitionActionPerformed
        comboTeam.setModel(new DefaultComboBoxModel(getTeamList()));
    }//GEN-LAST:event_comboCompetitionActionPerformed

    private void comboTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTeamActionPerformed
        String teamName = comboTeam.getSelectedItem().toString();

        for (IClubTeamDto ct : cTeams) {
            if (ct.getName().equals(teamName)) {
                team = ct;
            }
        }
        setTeamMemberList();

        IClubTeamDto compTeam = controller.getCompetitionTeam(team);
        List<Integer> playerInt = compTeam.getPlayerList();
        oldTeam = controller.getPlayers(playerInt);
        newTeam = controller.getPlayers(playerInt);
        setCompTeamList();
    }//GEN-LAST:event_comboTeamActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //List Models
        ListModel cTeamModel = listCompTeam.getModel();
        ListModel origModel = listTeam.getModel();

        //arrays to store teams, list to save new state of origin
        Object[] origSel = listTeam.getSelectedValues();
        Object[] cTeam = new Object[cTeamModel.getSize() + origSel.length];
        List<Object> tmpOrig = new LinkedList<>();

        for (int i = 0; i < origModel.getSize(); i++) {
            tmpOrig.add(origModel.getElementAt(i));
        }
        for (int i = 0; i < cTeamModel.getSize(); i++) {
            cTeam[i] = cTeamModel.getElementAt(i);
        }
        for (int i = cTeamModel.getSize(); i < cTeam.length; i++) {
            cTeam[i] = origSel[i - cTeamModel.getSize()];
            newTeam.add((IPlayerDto) origSel[i - cTeamModel.getSize()]);
            teamMember.remove((IPlayerDto) origSel[i-cTeamModel.getSize()]);   //remove from available team member list
            
            tmpOrig.remove(origSel[i - cTeamModel.getSize()]);
        }
        Object[] newOrigSel = tmpOrig.toArray();

        listCompTeam.setListData(cTeam);
        listTeam.setListData(newOrigSel);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
         //List Models
        ListModel compTModel = listCompTeam.getModel();
        ListModel teamModel = listTeam.getModel();

        //arrays to store teams, list to save new state of competition team                            
        Object[] cTeamSel = listCompTeam.getSelectedValues();                  //competitionteam
        Object[] origTeam = new Object[teamModel.getSize() + cTeamSel.length];  //team general
        List<Object> tmpTeam = new LinkedList<>();

        //Competition Team before removing
        for (int i = 0; i < compTModel.getSize(); i++) {
            tmpTeam.add(compTModel.getElementAt(i));
        }
        //add team data to teamlist
        for (int i = 0; i < teamModel.getSize(); i++) {
            origTeam[i] = teamModel.getElementAt(i);
        }
        //add selected from compTeam to Team
        for (int i = teamModel.getSize(); i < origTeam.length; i++) {
            origTeam[i] = cTeamSel[i - teamModel.getSize()];
            tmpTeam.remove(cTeamSel[i - teamModel.getSize()]);
        }

        for (int i = 0; i < cTeamSel.length; i++) {
            teamMember.add((IPlayerDto) cTeamSel[i]);
            newTeam.remove((IPlayerDto) cTeamSel[i]);  //remove from new team list
        }

        Object[] nTeam = tmpTeam.toArray();

        listCompTeam.setListData(nTeam);
        listTeam.setListData(origTeam);
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        IClubTeamDto oldCompTeam = controller.getCompetitionTeam(team);   
        IClubTeamDto newCompTeam = oldCompTeam;
        
        List<Integer> newPlayInt = new LinkedList<>();
        for(IPlayerDto player: newTeam){
            newPlayInt.add(player.getId());
        }                
        newCompTeam.setPlayerList(newPlayInt);        
        
        controller.setCompetitonTeam(competition, oldCompTeam, newCompTeam);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void setTeamMemberList() {
        List<Integer> playerInt = team.getPlayerList();
        teamMember = controller.getPlayers(playerInt);
        final String[] players = new String[teamMember.size()];

        for (int i = 0; i < players.length; i++) {
            players[i] = teamMember.get(i).toString();
        }

        listTeam.setModel(new AbstractListModel() {
            String[] strings = players;

            @Override
            public int getSize() {
                return strings.length;
            }

            @Override
            public Object getElementAt(int i) {
                return strings[i];
            }
        });
    }
    
    private void setCompTeamList() {

        final String[] topTeam = new String[newTeam.size()];
        for (int i = 0; i < topTeam.length; i++) {
            topTeam[i] = newTeam.get(i).toString();
        }

        listCompTeam.setModel(new AbstractListModel() {
            String[] strings = topTeam;

            @Override
            public int getSize() {
                return strings.length;
            }

            @Override
            public Object getElementAt(int i) {
                return strings[i];
            }
        });
    }
    
    private String[] getCompetitionList() {
        List<ICompetitionDto> compList = controller.getCompetition();
        String[] compArray = new String[compList.size()];

        for (int i = 0; i < compList.size(); i++) {
            //TODO: check how to name it
            compArray[i] = compList.get(i).toString();
        }
        return compArray;
    }

    private String[] getTeamList() {
        competition = (ICompetitionDto) comboCompetition.getSelectedItem(); //TODO: get compname
        List<Integer> allTeams = competition.getTeamList();

        cTeams = controller.getClubTeams(allTeams);
        String[] cTeamArray = new String[cTeams.size()];

        for (int i = 0; i < cTeamArray.length; i++) {
            cTeamArray[i] = cTeams.get(i).getName();
        }
        return cTeamArray;
    }
    
    public JPanel getPanel(){
        return panelChangeTeam;
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox comboCompetition;
    private javax.swing.JComboBox comboTeam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCompetitionSel;
    private javax.swing.JLabel lblMembers;
    private javax.swing.JLabel lblSelTeam;
    private javax.swing.JList listCompTeam;
    private javax.swing.JList listTeam;
    private javax.swing.JPanel panelChangeTeam;
    private javax.swing.JScrollPane scrollCompTeam;
    private javax.swing.JScrollPane scrollTeam;
    // End of variables declaration//GEN-END:variables
}
