delete from Country;

insert into Country (Name, Description) VALUES('Afghanistan', 'Islamic Republic of Afghanistan');
insert into Country (Name, Description) VALUES('Albania', 'Republic of Albania');
insert into Country (Name, Description) VALUES('Algeria', 'People s Democratic Republic of Algeria');
insert into Country (Name, Description) VALUES('Andorra', 'Principality of Andorra');
insert into Country (Name, Description) VALUES('Angola', 'Republic of Angola');
insert into Country (Name, Description) VALUES('Antigua and Barbuda', '');
insert into Country (Name, Description) VALUES('Argentina', 'Argentine Republic');
insert into Country (Name, Description) VALUES('Armenia', 'Republic of Armenia');
insert into Country (Name, Description) VALUES('Australia', 'Commonwealth of Australia');
insert into Country (Name, Description) VALUES('Austria', 'Republic of Austria');
insert into Country (Name, Description) VALUES('Azerbaijan', 'Republic of Azerbaijan');
insert into Country (Name, Description) VALUES('Bahamas', 'Commonwealth of The Bahamas');
insert into Country (Name, Description) VALUES('Bahrain', 'Kingdom of Bahrain');
insert into Country (Name, Description) VALUES('Bangladesh', 'People s Republic of Bangladesh');
insert into Country (Name, Description) VALUES('Barbados', '');
insert into Country (Name, Description) VALUES('Belarus', 'Republic of Belarus');
insert into Country (Name, Description) VALUES('Belgium', 'Kingdom of Belgium');
insert into Country (Name, Description) VALUES('Belize', '');
insert into Country (Name, Description) VALUES('Benin', 'Republic of Benin');
insert into Country (Name, Description) VALUES('Bhutan', 'Kingdom of Bhutan');
insert into Country (Name, Description) VALUES('Bolivia', 'Plurinational State of Bolivia');
insert into Country (Name, Description) VALUES('Bosnia and Herzegovina', '');
insert into Country (Name, Description) VALUES('Botswana', 'Republic of Botswana');
insert into Country (Name, Description) VALUES('Brazil', 'Federative Republic of Brazil');
insert into Country (Name, Description) VALUES('Brunei', 'State of Brunei, Abode of Peace');
insert into Country (Name, Description) VALUES('Bulgaria', 'Republic of Bulgaria');
insert into Country (Name, Description) VALUES('Burkina Faso', '');
insert into Country (Name, Description) VALUES('Burma', 'Republic of the Union of Myanmar');
insert into Country (Name, Description) VALUES('Burundi', 'Republic of Burundi');
insert into Country (Name, Description) VALUES('Cambodia', 'Kingdom of Cambodia');
insert into Country (Name, Description) VALUES('Cameroon', 'Republic of Cameroon');
insert into Country (Name, Description) VALUES('Canada', '');
insert into Country (Name, Description) VALUES('Cape Verde', 'Republic of Cape Verde');
insert into Country (Name, Description) VALUES('Central African Republic', '');
insert into Country (Name, Description) VALUES('Chad', 'Republic of Chad');
insert into Country (Name, Description) VALUES('Chile', 'Republic of Chile');
insert into Country (Name, Description) VALUES('China', 'People s Republic of China');
insert into Country (Name, Description) VALUES('Colombia', 'Republic of Colombia');
insert into Country (Name, Description) VALUES('Comoros', 'Union of the Comoros');
insert into Country (Name, Description) VALUES('Congo, Democratic Republic of the (Congo-Kinshasa)', '');
insert into Country (Name, Description) VALUES('Congo, Republic of the (Congo-Brazzaville)', '');
insert into Country (Name, Description) VALUES('Costa Rica', 'Republic of Costa Rica');
insert into Country (Name, Description) VALUES('Côte d Ivoire', 'Republic of Côte d Ivoire (Ivory Coast)');
insert into Country (Name, Description) VALUES('Croatia', 'Republic of Croatia');
insert into Country (Name, Description) VALUES('Cuba', 'Republic of Cuba');
insert into Country (Name, Description) VALUES('Cyprus', 'Republic of Cyprus');
insert into Country (Name, Description) VALUES('Czech Republic', '');
insert into Country (Name, Description) VALUES('Denmark', 'Kingdom of Denmark');
insert into Country (Name, Description) VALUES('The Danish Realm also includes two self-governing territories:', '');
insert into Country (Name, Description) VALUES('Faroe Islands (Føroyar/Færøerne)', '');
insert into Country (Name, Description) VALUES('Greenland (Kalaallit Nunaat/Grønland)', '');
insert into Country (Name, Description) VALUES('Djibouti', 'Republic of Djibouti');
insert into Country (Name, Description) VALUES('Dominica', 'Commonwealth of Dominica');
insert into Country (Name, Description) VALUES('Dominican Republic', '');
insert into Country (Name, Description) VALUES('East Timor', 'Democratic Republic of Timor-Leste');
insert into Country (Name, Description) VALUES('Ecuador', 'Republic of Ecuador');
insert into Country (Name, Description) VALUES('Egypt', 'Arab Republic of Egypt');
insert into Country (Name, Description) VALUES('El Salvador', 'Republic of El Salvador');
insert into Country (Name, Description) VALUES('Equatorial Guinea', 'Republic of Equatorial Guinea');
insert into Country (Name, Description) VALUES('Eritrea', 'State of Eritrea');
insert into Country (Name, Description) VALUES('Estonia', 'Republic of Estonia');
insert into Country (Name, Description) VALUES('Ethiopia', 'Federal Democratic Republic of Ethiopia');
insert into Country (Name, Description) VALUES('Fiji', 'Republic of Fiji');
insert into Country (Name, Description) VALUES('Finland', 'Republic of Finland');
insert into Country (Name, Description) VALUES('France', 'French Republic');
insert into Country (Name, Description) VALUES('Gabon', 'Gabonese Republic');
insert into Country (Name, Description) VALUES('The Gambia', 'Republic of The Gambia');
insert into Country (Name, Description) VALUES('Georgia', '');
insert into Country (Name, Description) VALUES('Germany', 'Federal Republic of Germany');
insert into Country (Name, Description) VALUES('Ghana', 'Republic of Ghana');
insert into Country (Name, Description) VALUES('Greece', 'Hellenic Republic');
insert into Country (Name, Description) VALUES('Grenada', '');
insert into Country (Name, Description) VALUES('Guatemala', 'Republic of Guatemala');
insert into Country (Name, Description) VALUES('Guinea', 'Republic of Guinea');
insert into Country (Name, Description) VALUES('Guinea-Bissau', 'Republic of Guinea-Bissau');
insert into Country (Name, Description) VALUES('Guyana', 'Co-operative Republic of Guyana');
insert into Country (Name, Description) VALUES('Haiti', 'Republic of Haiti');
insert into Country (Name, Description) VALUES('Honduras', 'Republic of Honduras');
insert into Country (Name, Description) VALUES('Hungary', '');
insert into Country (Name, Description) VALUES('Iceland', '');
insert into Country (Name, Description) VALUES('India', 'Republic of India');
insert into Country (Name, Description) VALUES('Indonesia', 'Republic of Indonesia');
insert into Country (Name, Description) VALUES('Iran', 'Islamic Republic of Iran');
insert into Country (Name, Description) VALUES('Iraq', 'Republic of Iraq');
insert into Country (Name, Description) VALUES('Ireland', '');
insert into Country (Name, Description) VALUES('Israel', '');
insert into Country (Name, Description) VALUES('Italy', 'Italian Republic');
insert into Country (Name, Description) VALUES('Jamaica', '');
insert into Country (Name, Description) VALUES('Japan', '');
insert into Country (Name, Description) VALUES('Jordan', 'Hashemite Kingdom of Jordan');
insert into Country (Name, Description) VALUES('Kazakhstan', 'Republic of Kazakhstan');
insert into Country (Name, Description) VALUES('Kenya', 'Republic of Kenya');
insert into Country (Name, Description) VALUES('Kiribati', 'Republic of Kiribati');
insert into Country (Name, Description) VALUES('Korea, North', '');
insert into Country (Name, Description) VALUES('Korea, South', '');
insert into Country (Name, Description) VALUES('Kosovo → Kosovo', '');
insert into Country (Name, Description) VALUES('Kuwait', 'State of Kuwait');
insert into Country (Name, Description) VALUES('Kyrgyzstan', 'Kyrgyz Republic');
insert into Country (Name, Description) VALUES('Laos', 'Lao People s Democratic Republic');
insert into Country (Name, Description) VALUES('Latvia', 'Republic of Latvia');
insert into Country (Name, Description) VALUES('Lebanon', 'Lebanese Republic');
insert into Country (Name, Description) VALUES('Lesotho', 'Kingdom of Lesotho');
insert into Country (Name, Description) VALUES('Liberia', 'Republic of Liberia');
insert into Country (Name, Description) VALUES('Libya', '');
insert into Country (Name, Description) VALUES('Liechtenstein', 'Principality of Liechtenstein');
insert into Country (Name, Description) VALUES('Lithuania', 'Republic of Lithuania');
insert into Country (Name, Description) VALUES('Luxembourg', 'Grand Duchy of Luxembourg');
insert into Country (Name, Description) VALUES('Macedonia', '');
insert into Country (Name, Description) VALUES('Madagascar', 'Republic of Madagascar');
insert into Country (Name, Description) VALUES('Malawi', 'Republic of Malawi');
insert into Country (Name, Description) VALUES('Malaysia', '');
insert into Country (Name, Description) VALUES('Maldives', 'Republic of Maldives');
insert into Country (Name, Description) VALUES('Mali', 'Republic of Mali');
insert into Country (Name, Description) VALUES('Malta', 'Republic of Malta');
insert into Country (Name, Description) VALUES('Marshall Islands', 'Republic of the Marshall Islands');
insert into Country (Name, Description) VALUES('Mauritania', 'Islamic Republic of Mauritania');
insert into Country (Name, Description) VALUES('Mauritius', 'Republic of Mauritius');
insert into Country (Name, Description) VALUES('Mexico', 'United Mexican States');
insert into Country (Name, Description) VALUES('Micronesia, Federated States of', '');
insert into Country (Name, Description) VALUES('Moldova', 'Republic of Moldova');
insert into Country (Name, Description) VALUES('Monaco', 'Principality of Monaco');
insert into Country (Name, Description) VALUES('Mongolia', '');
insert into Country (Name, Description) VALUES('Montenegro', '');
insert into Country (Name, Description) VALUES('Morocco', 'Kingdom of Morocco');
insert into Country (Name, Description) VALUES('Mozambique', 'Republic of Mozambique');
insert into Country (Name, Description) VALUES('Namibia', 'Republic of Namibia');
insert into Country (Name, Description) VALUES('Nauru', 'Republic of Nauru');
insert into Country (Name, Description) VALUES('Nepal', 'Federal Democratic Republic of Nepal');
insert into Country (Name, Description) VALUES('Netherlands', 'Kingdom of the Netherlands');
insert into Country (Name, Description) VALUES('New Zealand', '');
insert into Country (Name, Description) VALUES('Nicaragua', 'Republic of Nicaragua');
insert into Country (Name, Description) VALUES('Niger', 'Republic of Niger');
insert into Country (Name, Description) VALUES('Nigeria', 'Federal Republic of Nigeria');
insert into Country (Name, Description) VALUES('Northern Cyprus → Northern Cyprus', '');
insert into Country (Name, Description) VALUES('North Korea → Korea, North', '');
insert into Country (Name, Description) VALUES('Norway', 'Kingdom of Norway');
insert into Country (Name, Description) VALUES('Oman', 'Sultanate of Oman');
insert into Country (Name, Description) VALUES('Pakistan', 'Islamic Republic of Pakistan');
insert into Country (Name, Description) VALUES('Palau', 'Republic of Palau');
insert into Country (Name, Description) VALUES('Panama', 'Republic of Panama');
insert into Country (Name, Description) VALUES('Papua New Guinea', 'Independent State of Papua New Guinea');
insert into Country (Name, Description) VALUES('Paraguay', 'Republic of Paraguay');
insert into Country (Name, Description) VALUES('Peru', 'Republic of Peru');
insert into Country (Name, Description) VALUES('Philippines', 'Republic of the Philippines');
insert into Country (Name, Description) VALUES('Poland', 'Republic of Poland');
insert into Country (Name, Description) VALUES('Portugal', 'Portuguese Republic');
insert into Country (Name, Description) VALUES('Pridnestrovie → Transnistria', '');
insert into Country (Name, Description) VALUES('Qatar', 'State of Qatar');
insert into Country (Name, Description) VALUES('Romania', '');
insert into Country (Name, Description) VALUES('Russia', 'Russian Federation');
insert into Country (Name, Description) VALUES('Rwanda', 'Republic of Rwanda');
insert into Country (Name, Description) VALUES('Saint Kitts and Nevis', 'Federation of Saint Kitts and Nevis');
insert into Country (Name, Description) VALUES('Saint Lucia', '');
insert into Country (Name, Description) VALUES('Saint Vincent and the Grenadines', '');
insert into Country (Name, Description) VALUES('Samoa', 'Independent State of Samoa');
insert into Country (Name, Description) VALUES('San Marino', 'Republic of San Marino');
insert into Country (Name, Description) VALUES('São Tomé and Príncipe', 'Democratic Republic of São Tomé and Príncipe');
insert into Country (Name, Description) VALUES('Saudi Arabia', 'Kingdom of Saudi Arabia');
insert into Country (Name, Description) VALUES('Senegal', 'Republic of Senegal');
insert into Country (Name, Description) VALUES('Serbia', 'Republic of Serbia');
insert into Country (Name, Description) VALUES('Seychelles', 'Republic of Seychelles');
insert into Country (Name, Description) VALUES('Sierra Leone', 'Republic of Sierra Leone');
insert into Country (Name, Description) VALUES('Singapore', 'Republic of Singapore');
insert into Country (Name, Description) VALUES('Slovakia', 'Slovak Republic');
insert into Country (Name, Description) VALUES('Slovenia', 'Republic of Slovenia');
insert into Country (Name, Description) VALUES('Solomon Islands', '');
insert into Country (Name, Description) VALUES('Somalia', 'Federal Republic of Somalia');
insert into Country (Name, Description) VALUES('South Africa', 'Republic of South Africa');
insert into Country (Name, Description) VALUES('South Sudan', 'Republic of South Sudan');
insert into Country (Name, Description) VALUES('Spain', 'Kingdom of Spain');
insert into Country (Name, Description) VALUES('Sri Lanka', 'Democratic Socialist Republic of Sri Lanka');
insert into Country (Name, Description) VALUES('Sudan', 'Republic of the Sudan');
insert into Country (Name, Description) VALUES('Sudan, South → South Sudan', '');
insert into Country (Name, Description) VALUES('Suriname', 'Republic of Suriname');
insert into Country (Name, Description) VALUES('Swaziland', 'Kingdom of Swaziland');
insert into Country (Name, Description) VALUES('Sweden', 'Kingdom of Sweden');
insert into Country (Name, Description) VALUES('Switzerland', 'Swiss Confederation');
insert into Country (Name, Description) VALUES('Syria', 'Syrian Arab Republic');
insert into Country (Name, Description) VALUES('Tajikistan', 'Republic of Tajikistan');
insert into Country (Name, Description) VALUES('Tanzania', 'United Republic of Tanzania');
insert into Country (Name, Description) VALUES('Thailand', 'Kingdom of Thailand');
insert into Country (Name, Description) VALUES('Togo', 'Togolese Republic');
insert into Country (Name, Description) VALUES('Tonga', 'Kingdom of Tonga');
insert into Country (Name, Description) VALUES('Trinidad and Tobago', 'Republic of Trinidad and Tobago');
insert into Country (Name, Description) VALUES('Tunisia', 'Republic of Tunisia');
insert into Country (Name, Description) VALUES('Turkey', 'Republic of Turkey');
insert into Country (Name, Description) VALUES('Turkmenistan', '');
insert into Country (Name, Description) VALUES('Tuvalu', '');
insert into Country (Name, Description) VALUES('Uganda', 'Republic of Uganda');
insert into Country (Name, Description) VALUES('Ukraine', '');
insert into Country (Name, Description) VALUES('United Arab Emirates', '');
insert into Country (Name, Description) VALUES('United Kingdom', 'United Kingdom of Great Britain and Northern Ireland');
insert into Country (Name, Description) VALUES('United States', 'United States of America');
insert into Country (Name, Description) VALUES('Uruguay', 'Oriental Republic of Uruguay');
insert into Country (Name, Description) VALUES('Uzbekistan', 'Republic of Uzbekistan');
insert into Country (Name, Description) VALUES('Vanuatu', 'Republic of Vanuatu');
insert into Country (Name, Description) VALUES('Vatican City', '');
insert into Country (Name, Description) VALUES('Venezuela', 'Bolivarian Republic of Venezuela');
insert into Country (Name, Description) VALUES('Vietnam', 'Socialist Republic of Vietnam');
insert into Country (Name, Description) VALUES('Yemen', 'Republic of Yemen');
insert into Country (Name, Description) VALUES('Zambia', 'Republic of Zambia');
insert into Country (Name, Description) VALUES('Zimbabwe', 'Republic of Zimbabwe');
insert into Country (Name, Description) VALUES('Abkhazia', '');
insert into Country (Name, Description) VALUES('Cook Islands', '');
insert into Country (Name, Description) VALUES('Kosovo', 'Republic of Kosovo');
insert into Country (Name, Description) VALUES('Nagorno-Karabakh', 'Nagorno-Karabakh Republic');
insert into Country (Name, Description) VALUES('Niue Member of some', '');
insert into Country (Name, Description) VALUES('Northern Cyprus', 'Turkish Republic of Northern Cyprus');
insert into Country (Name, Description) VALUES('Palestine', 'State of Palestine');
insert into Country (Name, Description) VALUES('Sahrawi Arab Democratic Republic', '');
insert into Country (Name, Description) VALUES('Somaliland', 'Republic of Somaliland');
insert into Country (Name, Description) VALUES('South Ossetia', 'Republic of South Ossetia');
insert into Country (Name, Description) VALUES('Taiwan', 'Republic of China Former');
insert into Country (Name, Description) VALUES('Transnistria', 'Transnistrian Moldovan Republic (Pridnestrovie, Trans-Dniester)');


