package presentation.forms.member;

import contract.ISearchChangeMember;
import dto.classes.*;
import dto.contract.*;
import java.awt.event.ActionEvent;
import java.util.*;
import javax.swing.*;
import javax.swing.event.*;
import javax.swing.table.TableModel;
import presentation.basics.*;
import presentation.forms.helper.SelectSportsHelper;
import services.*;

/**

 @author Lucia
 */
public class SearchMemberForm
        extends AbstractMainForm
{
    private boolean dataExists;
    private boolean adminPermission;
    ServiceClient client;
    ISearchChangeMember controller;
    IMember user;
    List<IRole> roles;
    IAddress address;
    ICountry country;
    IClubTeam clubTeam;
    private List<ITypeOfSport> typeOfSports;
    private List<ITypeOfSport> availableSports;
    private List<ITypeOfSport> selectedSports;
    private List<IMember> matchingMembers;

    /**
     Creates new form SearchMemb
     */
    public SearchMemberForm(AbstractForm form, ServiceClient client, IMember user)
            throws ServiceNotAvailableException
    {
        super(form);
        this.client = client;
        this.user = user;
        controller = this.client.getSearchChangeMemberService();
        initComponents();
    }

    /**
     This method is called from within the constructor to initialize the form.
     WARNING: Do NOT modify this code. The content of this method is always
     regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        paneSearch = new javax.swing.JPanel();
        txtfieldSearchMemb = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabMember = new javax.swing.JTable();
        paneMemberData = new javax.swing.JPanel();
        lblFName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblBirthDate = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        radioFemale = new javax.swing.JRadioButton();
        radioMale = new javax.swing.JRadioButton();
        lblEntryDate = new javax.swing.JLabel();
        lblTeam = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        radioAdmin = new javax.swing.JRadioButton();
        radioTrainer = new javax.swing.JRadioButton();
        radioPlayer = new javax.swing.JRadioButton();
        comboTeam = new javax.swing.JComboBox();
        lblLName = new javax.swing.JLabel();
        lblPostCode = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        txtfieldLName = new javax.swing.JTextField();
        txtfieldPostCode = new javax.swing.JTextField();
        txtfieldCountry = new javax.swing.JTextField();
        txtfieldMail = new javax.swing.JTextField();
        txtfieldFName = new javax.swing.JTextField();
        txtfieldAddress = new javax.swing.JTextField();
        txtfieldCity = new javax.swing.JTextField();
        txtfieldPhone = new javax.swing.JTextField();
        dateBirthday = new com.toedter.calendar.JDateChooser();
        dateEntry = new com.toedter.calendar.JDateChooser();
        lblMemberNr = new javax.swing.JLabel();
        txtfieldMemberNr = new javax.swing.JTextField();
        btnApplyChange = new javax.swing.JButton();
        radioCaretaker = new javax.swing.JRadioButton();
        radioDepHead = new javax.swing.JRadioButton();
        lblSport = new javax.swing.JLabel();
        txtFieldSports = new javax.swing.JTextField();
        btnAddSport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(848, 549));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSearchActionPerformed(evt);
            }
        });

        tabMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String []
            {
                "Membership Nr.", "First Name", "Last Name", "Birth Date", "Gender"
            }
        ));
        tabMember.getSelectionModel().addListSelectionListener(new ListSelectionListener()
        {
            @Override
            public void valueChanged(ListSelectionEvent e)
            {
                tableMemberValueChanged(e);
            }
        });
        jScrollPane1.setViewportView(tabMember);

        paneMemberData.setBorder(javax.swing.BorderFactory.createTitledBorder("Details"));

        lblFName.setText("First Name");

        lblAddress.setText("Address");

        lblCity.setText("City");

        lblPhone.setText("Phone");

        lblBirthDate.setText("Birth Date");

        lblGender.setText("Gender");

        radioFemale.setText("female");
        radioFemale.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                radioFemaleActionPerformed(evt);
            }
        });

        radioMale.setText("male");
        radioMale.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                radioMaleActionPerformed(evt);
            }
        });

        lblEntryDate.setText("Entry Date");

        lblTeam.setText("Team");

        lblRole.setText("Role");

        radioAdmin.setText("Admin");
        radioAdmin.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                radioAdminActionPerformed(evt);
            }
        });

        radioTrainer.setText("Trainer");
        radioTrainer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                radioTrainerActionPerformed(evt);
            }
        });

        radioPlayer.setText("Player");
        radioPlayer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                radioPlayerActionPerformed(evt);
            }
        });

        comboTeam.setModel(new javax.swing.DefaultComboBoxModel(getComboTeam()));
        comboTeam.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                comboTeamActionPerformed(evt);
            }
        });

        lblLName.setText("Last Name");

        lblPostCode.setText("Post Code");

        lblCountry.setText("Country");

        lblMail.setText("Mail");

        txtfieldPostCode.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtfieldPostCodeActionPerformed(evt);
            }
        });

        dateEntry.setEnabled(false);

        lblMemberNr.setText("Membership Nr.");

        txtfieldMemberNr.setEnabled(false);

        btnApplyChange.setText("Apply Changes");
        btnApplyChange.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnApplyChangeActionPerformed(evt);
            }
        });

        radioCaretaker.setText("Caretaker");
        radioCaretaker.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                radioCaretakerActionPerformed(evt);
            }
        });

        radioDepHead.setText("Department Head");
        radioDepHead.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                radioDepHeadActionPerformed(evt);
            }
        });

        lblSport.setText("Sport");

        txtFieldSports.setEnabled(false);

        btnAddSport.setText("Select Sports");
        btnAddSport.setInheritsPopupMenu(true);
        btnAddSport.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddSportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneMemberDataLayout = new javax.swing.GroupLayout(paneMemberData);
        paneMemberData.setLayout(paneMemberDataLayout);
        paneMemberDataLayout.setHorizontalGroup(
            paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMemberDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneMemberDataLayout.createSequentialGroup()
                        .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFName)
                            .addComponent(lblAddress)
                            .addComponent(lblCity)
                            .addComponent(lblPhone)
                            .addComponent(lblBirthDate)
                            .addComponent(lblEntryDate)
                            .addComponent(lblTeam)
                            .addComponent(lblSport))
                        .addGap(26, 26, 26)
                        .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paneMemberDataLayout.createSequentialGroup()
                                .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(paneMemberDataLayout.createSequentialGroup()
                                        .addComponent(txtFieldSports, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAddSport))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paneMemberDataLayout.createSequentialGroup()
                                        .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtfieldCity, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtfieldFName, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtfieldAddress, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtfieldPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(dateBirthday, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(dateEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(133, 133, 133)
                                        .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblGender)
                                            .addComponent(lblMail)
                                            .addGroup(paneMemberDataLayout.createSequentialGroup()
                                                .addComponent(lblLName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtfieldLName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneMemberDataLayout.createSequentialGroup()
                                                .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(paneMemberDataLayout.createSequentialGroup()
                                                        .addComponent(lblPostCode)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneMemberDataLayout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(lblCountry)
                                                        .addGap(21, 21, 21)))
                                                .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtfieldCountry, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                    .addComponent(txtfieldPostCode)
                                                    .addComponent(txtfieldMail)
                                                    .addGroup(paneMemberDataLayout.createSequentialGroup()
                                                        .addComponent(radioFemale)
                                                        .addGap(10, 10, 10)
                                                        .addComponent(radioMale))))
                                            .addGroup(paneMemberDataLayout.createSequentialGroup()
                                                .addComponent(lblMemberNr)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtfieldMemberNr)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(btnApplyChange))))
                    .addGroup(paneMemberDataLayout.createSequentialGroup()
                        .addComponent(lblRole)
                        .addGap(58, 58, 58)
                        .addComponent(radioAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioCaretaker)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioDepHead)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioTrainer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioPlayer)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paneMemberDataLayout.setVerticalGroup(
            paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMemberDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneMemberDataLayout.createSequentialGroup()
                        .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfieldFName)
                            .addComponent(txtfieldLName)
                            .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblFName)
                                .addComponent(lblLName)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneMemberDataLayout.createSequentialGroup()
                                .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAddress)
                                    .addComponent(lblPostCode)
                                    .addComponent(txtfieldPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCity)
                                    .addComponent(lblCountry)
                                    .addComponent(txtfieldCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPhone)
                                    .addComponent(lblMail)
                                    .addComponent(txtfieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBirthDate)
                                    .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblGender)
                                        .addComponent(radioFemale)
                                        .addComponent(radioMale))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneMemberDataLayout.createSequentialGroup()
                                .addComponent(txtfieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEntryDate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateEntry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMemberNr)
                        .addComponent(txtfieldMemberNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioTrainer)
                        .addComponent(radioPlayer)
                        .addComponent(radioCaretaker)
                        .addComponent(radioDepHead))
                    .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRole)
                        .addComponent(radioAdmin)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSport)
                    .addComponent(txtFieldSports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddSport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTeam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnApplyChange)
                .addContainerGap())
        );

        javax.swing.GroupLayout paneSearchLayout = new javax.swing.GroupLayout(paneSearch);
        paneSearch.setLayout(paneSearchLayout);
        paneSearchLayout.setHorizontalGroup(
            paneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
                    .addGroup(paneSearchLayout.createSequentialGroup()
                        .addComponent(txtfieldSearchMemb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)
                        .addGap(0, 557, Short.MAX_VALUE))
                    .addComponent(paneMemberData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        paneSearchLayout.setVerticalGroup(
            paneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfieldSearchMemb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paneMemberData, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfieldPostCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldPostCodeActionPerformed
    }//GEN-LAST:event_txtfieldPostCodeActionPerformed

    private void comboTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTeamActionPerformed
        String name = comboTeam.getSelectedItem().toString();

        setClubTeam(name);
    }//GEN-LAST:event_comboTeamActionPerformed

    private void radioAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioAdminActionPerformed

    private void radioFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFemaleActionPerformed
        genderActionPerformed(evt);
    }//GEN-LAST:event_radioFemaleActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if (txtfieldSearchMemb.getText() == null)
        {
            JOptionPane.showMessageDialog(parent, "Please enter a name!");
        }
        else
        {
            matchingMembers = controller.getMatchingMembers(txtfieldSearchMemb.getText());

            if (matchingMembers == null || matchingMembers.isEmpty())
            {
                JOptionPane.showMessageDialog(parent, "Your entry ' " + txtfieldSearchMemb.getText() + "' could not be found!");
            }
            else
            {
                TableModel tableModel = tabMember.getModel();

                for (int row = 0; row < matchingMembers.size(); row++)
                {
                    IMember tmpMember = matchingMembers.remove(row);

                    tableModel.setValueAt(tmpMember.getId().toString(), row, 0);
                    tableModel.setValueAt(tmpMember.getPrename(), row, 1);
                    tableModel.setValueAt(tmpMember.getLastname(), row, 2);
                    tableModel.setValueAt(tmpMember.getDateOfBirth().toString(), row, 3);

                    tableModel.setValueAt(tmpMember.getGender() ? "female" : "male", row, 4);
                }
                tabMember.setModel(tableModel);
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tableMemberValueChanged(ListSelectionEvent e)
    {
        controller.setSelectedMember(matchingMembers.get(tabMember.getSelectedRow()));

        updateDetailPane();
    }

    private void btnApplyChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyChangeActionPerformed
        if (dataExists)
        {
            updateMemberData();
            //TODO: Throw exception in case of an error !!!!!
        }
        else
        {
            JOptionPane.showMessageDialog(parent, "There is no data to change!");
        }
    }//GEN-LAST:event_btnApplyChangeActionPerformed

    private void radioMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMaleActionPerformed
        genderActionPerformed(evt);
    }//GEN-LAST:event_radioMaleActionPerformed

    private void radioTrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTrainerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioTrainerActionPerformed

    private void radioPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPlayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPlayerActionPerformed

    private void radioCaretakerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCaretakerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCaretakerActionPerformed

    private void radioDepHeadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDepHeadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioDepHeadActionPerformed

    private void btnAddSportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSportActionPerformed
        if (radioTrainer.isSelected() || radioPlayer.isSelected())
        {
            //open new frame which enables selection of more sports
            SelectSportsHelper selectSportsHelper = new SelectSportsHelper(availableSports, selectedSports, this);
        }
        else
        {
            JOptionPane.showMessageDialog(parent, "Member is no player or trainer!");
        }
    }//GEN-LAST:event_btnAddSportActionPerformed

    @Override
    public void setTxtFieldSports(List<ITypeOfSport> selection)
    {
        this.selectedSports = selection;

        StringBuilder sb = new StringBuilder(selectedSports.size());
        for (ITypeOfSport s : selectedSports)
        {
            sb.append(s);
            sb.append(", ");
        }
        sb.delete(sb.length() - 2, sb.length());    //TODO check if this works 

        txtFieldSports.setText(sb.toString());
    }

    private void setSelectedSports(IRole role)
    {
        List<Integer> typeOfSportsID = null;

        if (role instanceof ITrainer)
        {
            ITrainer tmp = (ITrainer) role;
            typeOfSportsID = tmp.getTypeOfSportList();
        }
        else
        {
            IPlayer tmp = (IPlayer) role;
            typeOfSportsID = tmp.getTypeOfSportList();
        }

        //add members sports to his/her selectedSportsList
        for (ITypeOfSport tos : typeOfSports)
        {
            for (Integer i : typeOfSportsID)
            {
                if ((tos.getId()).equals(i))
                {
                    selectedSports.add(tos);
                }
            }
        }
    }

    private List<Integer> getSelectedSports()
    {
        List<Integer> tosIDs = new LinkedList<>();

        for (ITypeOfSport tos : typeOfSports)
        {
            for (ITypeOfSport s : selectedSports)
            {
                if (s.equals(tos))
                {
                    tosIDs.add(tos.getId());
                }
            }
        }
        return tosIDs;
    }

    private void updateDetailPane()
    {
        dataExists = true;

        List<Integer> sports = new LinkedList<>();

        for (IRole role : controller.getRoles(controller.getSelectedMember().getId()))
        {
            if (role instanceof ITrainer)
            {
                for (Integer t : ((ITrainer) role).getTypeOfSportList())
                {
                    if (!sports.contains(t))
                    {
                        sports.add(t);
                    }
                }
            }
            else if (role instanceof IPlayer)
            {
                for (Integer t : ((IPlayer) role).getTypeOfSportList())
                {
                    if (!sports.contains(t))
                    {
                        sports.add(t);
                    }
                }
            }
        }

        availableSports.addAll(controller.getTypeOfSports(sports));

        IMember selectedMember = controller.getSelectedMember();
        txtfieldMemberNr.setText(selectedMember.getId().toString());
        txtfieldFName.setText(selectedMember.getPrename());
        txtfieldLName.setText(selectedMember.getLastname());
        txtfieldMail.setText(selectedMember.getEmailAddress());
        txtfieldPhone.setText(selectedMember.getTelephonenumber());

        address = controller.getAddress(selectedMember.getAddress());
        txtfieldAddress.setText(address.getStreet());
        //TODO: ADD AN EXTRA STREET NR FIELD
        //txtfieldStreetNr.setText(address.getStreetNumber());
        String postCode = Integer.toString(address.getPostalCode());
        txtfieldPostCode.setText(postCode);
        txtfieldCity.setText(address.getVillage());

        country = controller.getCountry(selectedMember.getNationality());
        txtfieldCountry.setText(country.getName());

        radioFemale.setSelected(selectedMember.getGender());

        dateEntry.setDate(selectedMember.getMemberFrom());
        dateBirthday.setDate(selectedMember.getDateOfBirth());

        for (IRole role : controller.getRoles(controller.getSelectedMember().getId()))
        {
            if (role instanceof IAdmin)
            {
                radioAdmin.setSelected(true);
                disableExtendedRadioSelection();
            }
            else if (role instanceof ICaretaker)
            {
                radioCaretaker.setSelected(true);
            }
            else if (role instanceof IDepartmentHead)
            {
                radioDepHead.setSelected(true);
            }
            else if (role instanceof ITrainer)
            {
                radioTrainer.setSelected(true);
                setSelectedSports(role);

                setTxtFieldSports(controller.getTypeOfSports(((ITrainer) role).getTypeOfSportList()));
            }
            else if (role instanceof IPlayer)
            {
                radioPlayer.setSelected(true);
                setSelectedSports(role);

                setTxtFieldSports(controller.getTypeOfSports(((IPlayer) role).getTypeOfSportList()));
            }
        }

        comboTeam.setModel(new DefaultComboBoxModel());
        //    comboTeam.setModel(new DefaultComboBoxModel(getComboTeam()));

        //focus auf team dessen selectedMember momentan teil ist
    }

    private void updateMemberData()
    {
        IMember selectedMember = controller.getSelectedMember();

        selectedMember.setPrename(txtfieldFName.getText());
        selectedMember.setLastname(txtfieldLName.getText());
        selectedMember.setDateOfBirth(dateBirthday.getDate());
        selectedMember.setMemberFrom(dateEntry.getDate());
        selectedMember.setTelephonenumber(txtfieldPhone.getText());
        selectedMember.setEmailAddress(txtfieldMail.getText());
        //member.setId(Integer.parseInt(txtfieldMemberNr.getText()));

        address.setStreet(txtfieldAddress.getText());
        address.setPostalCode(Integer.parseInt(txtfieldPostCode.getText()));
        address.setVillage(txtfieldCity.getText());
        country.setName(txtfieldCountry.getText());
        selectedMember.setNationality(country.getId());

        selectedMember.setGender(radioFemale.isSelected());

        //   department = (IDepartment) comboDepartment.getSelectedItem();

        //get selected roles
        if (adminPermission)
        {
            if (radioAdmin.isSelected())
            {
                roles.add(new Admin());
            }
            if (radioCaretaker.isSelected())
            {
                roles.add(new Caretaker());
            }
            if (radioDepHead.isSelected())
            {
                roles.add(new DepartmentHead());
            }
            if (radioTrainer.isSelected())
            {
                ITrainer trainer = new Trainer();
                roles.add(trainer);
                trainer.setTypeOfSportList(getSelectedSports());
            }
        }

        if (radioPlayer.isSelected())
        {
            IPlayer player = null;
            roles.add(player);
            player.setTypeOfSportList(getSelectedSports());
        }

        List<Integer> roleInt = new LinkedList<>();
        for (IRole role : roles)
        {
            roleInt.add(role.getId());
        }
        selectedMember.setRoleList(roleInt);

        //make sure clubTeam is set right
        setClubTeam(comboTeam.getSelectedItem().toString());

        controller.setNewMember(selectedMember, address, clubTeam, roles.get(roles.size() - 1));
    }

//    private String[] getComboTeam()
//    {
//        List<String> result = new LinkedList<>();
//
//        if (department != null)
//        {
//            List<Integer> cTeamInt = department.getClubTeamList();
//
//            for (IClubTeam c : controller.getClubTeams(cTeamInt))
//            {
//                result.add(c.getName());
//            }
//        }
//
//        return result.toArray(new String[10]);
//    }
//    private void setClubTeam(String name)
//    {
//        List<Integer> cTeamInt = department.getClubTeamList();
//        List<IClubTeam> cTeamList = controller.getClubTeams(cTeamInt);
//
//        for (int i = 0; i < cTeamList.size(); i++)
//        {
//            if (cTeamList.get(i).getName().equals(name))
//            {
//                clubTeam = cTeamList.get(i);
//            }
//        }
//    }
    private void genderActionPerformed(ActionEvent evt)
    {
        if (evt.getSource() == radioFemale)
        {
            radioMale.setEnabled(!radioFemale.isSelected());
        }
        else
        {
            radioFemale.setEnabled(!radioMale.isSelected());
        }
    }

    private void disableExtendedRadioSelection()
    {
        radioAdmin.setEnabled(false);
        radioCaretaker.setEnabled(false);
        radioDepHead.setEnabled(false);
        radioTrainer.setEnabled(false);
    }

    public JPanel getPanel()
    {
        return paneSearch;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSport;
    private javax.swing.JButton btnApplyChange;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox comboTeam;
    private com.toedter.calendar.JDateChooser dateBirthday;
    private com.toedter.calendar.JDateChooser dateEntry;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBirthDate;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblEntryDate;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblMemberNr;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPostCode;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSport;
    private javax.swing.JLabel lblTeam;
    private javax.swing.JPanel paneMemberData;
    private javax.swing.JPanel paneSearch;
    private javax.swing.JRadioButton radioAdmin;
    private javax.swing.JRadioButton radioCaretaker;
    private javax.swing.JRadioButton radioDepHead;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JRadioButton radioPlayer;
    private javax.swing.JRadioButton radioTrainer;
    private javax.swing.JTable tabMember;
    private javax.swing.JTextField txtFieldSports;
    private javax.swing.JTextField txtfieldAddress;
    private javax.swing.JTextField txtfieldCity;
    private javax.swing.JTextField txtfieldCountry;
    private javax.swing.JTextField txtfieldFName;
    private javax.swing.JTextField txtfieldLName;
    private javax.swing.JTextField txtfieldMail;
    private javax.swing.JTextField txtfieldMemberNr;
    private javax.swing.JTextField txtfieldPhone;
    private javax.swing.JTextField txtfieldPostCode;
    private javax.swing.JTextField txtfieldSearchMemb;
    // End of variables declaration//GEN-END:variables
}
